# Generated by Django 5.2 on 2025-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctorprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default='2025-01-01 09:30'),
            preserve_default=False,
        ),
    ]
